name: Android CI
on: [push, pull_request]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: '11'
                  distribution: 'adopt'
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: Build with Gradle
              run: ./gradlew clean lintDebug assembleRelease
            - name: Upload build artifacts
              uses: actions/upload-artifact@v3
              with:
                  path: |
                      ./payment-demo/build/outputs/apk/
                      ./**/build/reports/lint-results.xml
                      ./**/build/reports/lint-results-*.html
            - name: Verification
              run: ./gradlew testDebug
            - name: Upload code coverage results
              uses: actions/upload-artifact@v3
              with:
                  path: ./**/build/test-results/**/TEST-*.xml

